base: &base
  adapter: postgresql
  encoding: utf8
  username: deepankanchitragupt
  password:
  host: 127.0.0.1
  pool: 5

development:
  <<: *base
  database: rating_development
  #database: edge_development

test:
  <<: *base
  database: rating_test

staging:
  <<: *base
  database: rating_staging

production:
  <<: *base
  database: rating_production